echo Primitive : double
echo Primitive : char
echo Primitive : boolean
echo Primitive : int
echo Referenced : String
echo Primitive : boolean
echo Primitive : double
echo Primitive : char
echo Referenced : String